version: '3.0'
 
services:

 backend-server:
    build: "./"
    container_name: backend-server
    ports:
      - 3000:3000
    depends_on:
      - mongodb
      
 mongodb:
    build: './database/'
    container_name: mongodb
    volumes:
      - 'mongodb_data:/data/db'
    ports:
      - 27017:27017
    
volumes:
  mongodb_data:
    driver: local